
DROP TABLE IF EXISTS FEEDBACK;
DROP TABLE IF EXISTS OFFER;
DROP TABLE IF EXISTS CENTRE_ADMINISTRATOR;
DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS DEALER_CENTRE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ADMINISTRATOR;
DROP TABLE IF EXISTS CITY;

CREATE TABLE ADMINISTRATOR
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(50) NOT NULL, 
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID, USERNAME)
);

CREATE TABLE CITY
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CITY_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CLIENT
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(50) NOT NULL, 
    PASSPORT VARCHAR(11) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    BALANCE INT DEFAULT 0,
    CITY_ID INT NOT NULL,
    AGE INT NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES CITY(ID),
    PRIMARY KEY(ID, USERNAME, PASSPORT)
);



CREATE TABLE DEALER_CENTRE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    ADRES TEXT NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    CITY_ID INT NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES CITY(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE CAR
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEALER_ID INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    BRAND VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    COSTDAY INT NOT NULL,
    COSTHOUR INT NOT NULL,
    IS_FREE INT NOT NULL,
    TRANSMISSION VARCHAR(10) NOT NULL,
    ENGINE VARCHAR(5) NOT NULL,
    SEATS INT NOT NULL,
    FORCE INT NOT NULL,
    OIL VARCHAR(5) NOT NULL,
    DRIVE VARCHAR(10) NOT NULL,
    DEPOSIT INT NOT NULL,
    YEAR INT NOT NULL,
    LINK TEXT NOT NULL,
    INFORMATION TEXT NOT NULL DEFAULT 'Это лучший автомобиль на свете!'
    FOREIGN KEY (DEALER_ID) REFERENCES DEALER_CENTRE(ID),
    PRIMARY KEY(ID)
);



CREATE TABLE CENTRE_ADMINISTRATOR
(
    DEALER_ID INT NOT NULL,
    ADMINISTRATOR_ID INT NOT NULL,
    ADMINISTRATOR_USERNAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (ADMINISTRATOR_ID, ADMINISTRATOR_USERNAME) REFERENCES ADMINISTRATOR(ID, USERNAME),
    FOREIGN KEY (DEALER_ID) REFERENCES DEALER_CENTRE(ID),
    PRIMARY KEY(DEALER_ID, ADMINISTRATOR_ID, ADMINISTRATOR_USERNAME)
);

CREATE TABLE OFFER
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID INT NOT NULL,
    CLIENT_USERNAME VARCHAR(50) NOT NULL,
    CLIENT_PASSPORT VARCHAR(11) NOT NULL,
    DEALER_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    HOURS_NUMBER INT NOT NULL,
    COST INT NOT NULL,
    IS_COMPLITED INT NOT NULL,
    HAVE_FEEDBACK INT NOT NULL,
    "DATE" DATE NOT NULL,
    "TIME" TIME NOT NULL,
    FOREIGN KEY(CLIENT_ID, CLIENT_PASSPORT, CLIENT_USERNAME) REFERENCES CLIENT(ID, PASSPORT, USERNAME),
    FOREIGN KEY (DEALER_ID) REFERENCES DEALER_CENTRE(ID),
    FOREIGN KEY (CAR_ID) REFERENCES CAR(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE FEEDBACK
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    OFFER_ID INT NOT NULL,
    STARS INT NOT NULL,
    INFORMATION TEXT DEFAULT ' ',
    DELAER_STARS INT NOT NULL,
    DEALER_INFORMATION TEXT DEFAULT ' ',
    FOREIGN KEY (OFFER_ID) REFERENCES OFFER(ID),
    PRIMARY KEY(ID, OFFER_ID)
);
